# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!

{ fetchNuGet }: [
  (fetchNuGet { pname = "FSharp.Control.AsyncSeq"; version = "3.0.2"; sha256 = "0g3fh39g5cj1g7y8fvn2vr3l2ifhsqsq3i775bbw94p6q5ahky4z"; })
  (fetchNuGet { pname = "Microsoft.Data.Sqlite"; version = "6.0.8"; sha256 = "031fgmmaj2ry3880xl8fqzsz5xbm5qpsxs6mfyqi57az29wilsv1"; })
  (fetchNuGet { pname = "Microsoft.Data.Sqlite.Core"; version = "6.0.8"; sha256 = "1q3rp78yni4mj8bgr5dg1s99mg0dh3rd2ha4f29vfhvp9gps5khi"; })
  (fetchNuGet { pname = "SQLitePCLRaw.bundle_e_sqlite3"; version = "2.0.6"; sha256 = "1ip0a653dx5cqybxg27zyz5ps31f2yz50g3jvz3vx39isx79gax3"; })
  (fetchNuGet { pname = "SQLitePCLRaw.core"; version = "2.0.6"; sha256 = "1w4iyg0v1v1z2m7akq7rv8lsgixp2m08732vr14vgpqs918bsy1i"; })
  (fetchNuGet { pname = "SQLitePCLRaw.lib.e_sqlite3"; version = "2.0.6"; sha256 = "16378rh1lcqxynf5qj0kh8mrsb0jp37qqwg4285kqc5pknvh1bx3"; })
  (fetchNuGet { pname = "SQLitePCLRaw.provider.e_sqlite3"; version = "2.0.6"; sha256 = "0chgrqyycb1kqnaxnhhfg0850b94blhzni8zn79c7ggb3pd2ykyz"; })
  (fetchNuGet { pname = "System.Memory"; version = "4.5.3"; sha256 = "0naqahm3wljxb5a911d37mwjqjdxv9l0b49p5dmfyijvni2ppy8a"; })
  (fetchNuGet { pname = "Vp.FSharp.Sql"; version = "1.0.47"; sha256 = "1xi1s9gj1h2kxphqk9jz15ai1yy698zbaxqv3k928wp87s5g8k9s"; })
]
