[<RequireQualifiedAccess>]
module rec FlyIo.GetApp

type InputVariables = { appName: string }

/// Organization that owns this app
type Organization =
    { id: string
      /// Organization name
      name: string }

type Region =
    { /// The name of this region
      name: string
      /// The IATA airport code for this region
      code: string }

/// A list of nodes.
type MachineIP =
    { /// ID of the object.
      id: string
      ip: string
      kind: string
      family: string }

type MachineIPConnection =
    { /// A list of nodes.
      nodes: Option<list<Option<MachineIP>>> }

/// A list of nodes.
type Machine =
    { name: string
      id: string
      ips: MachineIPConnection }

type MachineConnection =
    { /// A list of nodes.
      nodes: Option<list<Option<Machine>>> }

/// A list of nodes.
type Volume =
    { id: string
      name: string
      sizeGb: int
      state: string
      status: string
      usedBytes: string }

/// Volumes associated with app
type VolumeConnection =
    { /// A list of nodes.
      nodes: Option<list<Option<Volume>>> }

/// Find an app by name
type App =
    { appUrl: Option<string>
      createdAt: string
      deployed: bool
      /// Autogenerated hostname for this application
      hostname: Option<string>
      /// Unique application ID
      id: string
      /// The unique application name
      name: string
      /// Organization that owns this app
      organization: Organization
      regions: list<Region>
      /// Application status
      status: string
      machines: MachineConnection
      /// Volumes associated with app
      volumes: VolumeConnection }

type Query =
    { /// Find an app by name
      app: Option<App> }
