[<RequireQualifiedAccess>]
module rec FlyIo.GetApp

type InputVariables = { appName: string }

/// Organization that owns this app
type Organization =
    { id: string
      /// Organization name
      name: string }

type Region =
    { /// The name of this region
      name: string
      /// The IATA airport code for this region
      code: string }

/// Find an app by name
type App =
    { appUrl: Option<string>
      createdAt: string
      deployed: bool
      /// Autogenerated hostname for this application
      hostname: Option<string>
      /// Unique application ID
      id: string
      /// The unique application name
      name: string
      /// Organization that owns this app
      organization: Organization
      regions: list<Region>
      /// Application status
      status: string }

type Query =
    { /// Find an app by name
      app: Option<App> }
